### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by rapha8l** [naver/lispe#5]
Hi,

Thanks for Lispe
though it doesn't build on linux : 
`make all libs
`
`mkdir -p bin
mkdir -p objs
mkdir -p objs/jag
mkdir -p objs/testemojis
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/lispe.cxx -o objs/lispe.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/lispe.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/jagget.cxx -o objs/jagget.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/jagget.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/eval.cxx -o objs/eval.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/eval.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/elements.cxx -o objs/elements.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/elements.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/tools.cxx -o objs/tools.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/tools.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/systems.cxx -o objs/systems.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/systems.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/maths.cxx -o objs/maths.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/maths.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/strings.cxx -o objs/strings.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/strings.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/randoms.cxx -o objs/randoms.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/randoms.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/rgx.cxx -o objs/rgx.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/rgx.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/sockets.cxx -o objs/sockets.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/sockets.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/composing.cxx -o objs/composing.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/composing.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/ontology.cxx -o objs/ontology.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/ontology.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/sets.cxx -o objs/sets.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/sets.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/lists.cxx -o objs/lists.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/lists.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/dictionaries.cxx -o objs/dictionaries.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/dictionaries.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/straight_eval.cxx -o objs/straight_eval.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/straight_eval.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/tensors.cxx -o objs/tensors.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/tensors.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/jag.cxx -o objs/jag.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/jag.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/main.cxx -o objs/main.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/main.o] Error 127 (ignorée)
fPIC -std=c++11 -w -c -O3 -DPOSIXREGEX -I/usr/include/ -DUNIX  -Iinclude src/lispeditor.cxx -o objs/lispeditor.o
make: fPIC: N'est pas un dossier
make: [Makefile:22: objs/lispeditor.o] Error 127 (ignorée)
o bin/lispe objs/lispe.o objs/jagget.o objs/eval.o objs/elements.o objs/tools.o objs/systems.o objs/maths.o objs/strings.o objs/randoms.o objs/rgx.o objs/sockets.o objs/composing.o objs/ontology.o objs/sets.o objs/lists.o objs/dictionaries.o objs/straight_eval.o objs/tensors.o objs/jag.o objs/main.o objs/lispeditor.o -ldl -lpthread -L/usr/lib64/
make: o: N'est pas un dossier
make: [Makefile:34: lispe] Error 127 (ignorée)
ar rcs bin/liblispe.a objs/lispe.o objs/jagget.o objs/eval.o objs/elements.o objs/tools.o objs/systems.o objs/maths.o objs/strings.o objs/randoms.o objs/rgx.o objs/sockets.o objs/composing.o objs/ontology.o objs/sets.o objs/lists.o objs/dictionaries.o objs/straight_eval.o objs/tensors.o
ar: objs/lispe.o: Aucun fichier ou dossier de ce type
make: *** [Makefile:50: liblispe] Error 1
`

**Comment by clauderouxster** [comment]
Hello,

Please I apologise for the late answer, but I was on holidays and far from my computer.
I have corrected the error, which was situated in configure.py. Basically, the line to indicate the compiler was missing.

You can now launch: python configure.py to create a proper version of LispE...

**Comment by clauderouxster** [comment]
Of course you need to pull a new version...

**Comment by rapha8l** [comment]
Thanks :)
No problem for the delay, everyone has a life
It doesn't build on latest arch, i join the log 
Thanks !
[lispe.txt](https://github.com/naver/lispe/files/13820816/lispe.txt)

**Comment by ClaudeRoux** [comment]
Could you tell me which version of g++ you are using?

**Comment by ClaudeRoux** [comment]
I work on Windows, Mac OS and Centos and I never encountered this problem before... On en apprend tous les jours...
I have added the missing <cstdint> include to the incriminated files... Hope that it will solve these issues.
Thank you very much for your help and your patience, I really appreciate it...

**Comment by rapha8l** [comment]
a special thanks for you, i'm just trying :)
unfortunately there is still an error on gui building
[lispe.txt](https://github.com/naver/lispe/files/13833386/lispe.txt)

**Comment by ClaudeRoux** [comment]
We are getting closer... There seems to be a name conflict with X11 files. I have renamed the Complex class into Complexe to solve this issue.

**Comment by ClaudeRoux** [comment]
I re-read your lispe.txt and I also corrected the True function, which has been renamed into isTrue. The same for False...

**Comment by rapha8l** [comment]
Thanks a lot again
It works now
Centos is far behind in terms of packages version, maybe that's why you couldn't see the problem (just a guess)
Have a nice day

**Comment by ClaudeRoux** [comment]
By the way, you can also compile an editor that I have created: _make jag_
It is actually part of the lispe interpreter itself. If you type in: edit in lispe, you can switch to an editor mode, where all the last instructions can be edited.
You can activate the mouse as well in it with lispe -m ... or with Ctrl-x-m within the editor.
However, if your terminal is activated as VT100, the mouse might fail. In that case, you have two options:

a) You use -vt100: lispe -vt100
b) Or you uncomment in Makefile.in the line about the XTERM_VT100 and recompile.

jag is a very light but quite powerful editor, whose description is here: https://github.com/naver/lispe/wiki/1.2-Jag:-Terminal-Editor-With-Mouse-Support-and-Colour-Highlighting

**Comment by rapha8l** [comment]
Great, thanks for the explanation

**Comment by ClaudeRoux** [comment]
I also suggest this description of LispE as a Shell (https://github.com/naver/lispe/wiki/7.-Comme-Shell)
