### ISSUE TITLE
How to run a source file?

### ISSUE THREAD

**Issue by GerardSontag** [naver/lispe#6]
Sorry for this stupid question  how to run a source file from the REPL

**Comment by ClaudeRoux** [comment]
Goodness me, I missed you question...
It depends on which machines you run your code.
If you are on Windows or MacOS, you have access to a native GUI that you can use to run, debug and experiment with LispE.
On Windows it is usually installed in Navercorp in Programs, you will also find a command-line version
On MacOS, we have also both: A GUI versions (in Applications) and a command-line version in /user/local/bin/
On Linux, the only available version is compliled into bin.

To execute a program: lispe program.lsp
You can also edit a program from within lispe: lispe -e program.lsp
You can then do Ctrl-r to run it. You will then pass into a mode in which you will also have access to global variables.
